const NODE_ENV = process.env.NODE_ENV || 'development';

module.exports = {
	/** The environment to use when building the project */
	env: NODE_ENV,
	/** The full path to the project's root directory */
	basePath: __dirname,
	/** The name of the directory containing the application source code */
	srcDir: 'src',
	/** The file name of the application's entry point */
	main: 'main',
	/** The name of the directory in which to emit compiled assets */
	outDir: 'dist',
	/** The base path for all projects assets (relative to the website root) */
	publicPath: '/',
	/** Whether to generate sourcemaps */
	sourcemaps: true,
	/** A hash map of keys that the compiler should treat as external to the project */
	externals: {},
	/** A hash map of variables and their values to expose globally */
	globals: {
		localisation: {
			defaultLanguage: 'en',
			supportedLanguages: ['en', 'ru']
		},
		translateLanguages: {
			'af': 'afrikaans',
			'sq': 'albanian',
			'am': 'amharic',
			'ar': 'arabic',
			'hy': 'armenian',
			'az': 'azerbaijani',
			'eu': 'basque',
			'be': 'belarusian',
			'bn': 'bengali',
			'bs': 'bosnian',
			'bg': 'bulgarian',
			'ca': 'catalan',
			'ceb': 'cebuano',
			'ny': 'chichewa',
			'zh-cn': 'chinese_simplified',
			'zh-tw': 'chinese_traditional',
			'co': 'corsican',
			'hr': 'croatian',
			'cs': 'czech',
			'da': 'danish',
			'nl': 'dutch',
			'en': 'english',
			'eo': 'esperanto',
			'et': 'estonian',
			'tl': 'filipino',
			'fi': 'finnish',
			'fr': 'french',
			'fy': 'frisian',
			'gl': 'galician',
			'ka': 'georgian',
			'de': 'german',
			'el': 'greek',
			'gu': 'gujarati',
			'ht': 'haitian_creole',
			'ha': 'hausa',
			'haw': 'hawaiian',
			'iw': 'hebrew',
			'hi': 'hindi',
			'hmn': 'hmong',
			'hu': 'hungarian',
			'is': 'icelandic',
			'ig': 'igbo',
			'id': 'indonesian',
			'ga': 'irish',
			'it': 'italian',
			'ja': 'japanese',
			'jw': 'javanese',
			'kn': 'kannada',
			'kk': 'kazakh',
			'km': 'khmer',
			'ko': 'korean',
			'ku': 'kurdish_(kurmanji)',
			'ky': 'kyrgyz',
			'lo': 'lao',
			'la': 'latin',
			'lv': 'latvian',
			'lt': 'lithuanian',
			'lb': 'luxembourgish',
			'mk': 'macedonian',
			'mg': 'malagasy',
			'ms': 'malay',
			'ml': 'malayalam',
			'mt': 'maltese',
			'mi': 'maori',
			'mr': 'marathi',
			'mn': 'mongolian',
			'my': 'myanmar_(burmese)',
			'ne': 'nepali',
			'no': 'norwegian',
			'ps': 'pashto',
			'fa': 'persian',
			'pl': 'polish',
			'pt': 'portuguese',
			'ma': 'punjabi',
			'ro': 'romanian',
			'ru': 'russian',
			'sm': 'samoan',
			'gd': 'scots_gaelic',
			'sr': 'serbian',
			'st': 'sesotho',
			'sn': 'shona',
			'sd': 'sindhi',
			'si': 'sinhala',
			'sk': 'slovak',
			'sl': 'slovenian',
			'so': 'somali',
			'es': 'spanish',
			'su': 'sundanese',
			'sw': 'swahili',
			'sv': 'swedish',
			'tg': 'tajik',
			'ta': 'tamil',
			'te': 'telugu',
			'th': 'thai',
			'tr': 'turkish',
			'uk': 'ukrainian',
			'ur': 'urdu',
			'uz': 'uzbek',
			'vi': 'vietnamese',
			'cy': 'welsh',
			'xh': 'xhosa',
			'yi': 'yiddish',
			'yo': 'yoruba',
			'zu': 'zulu'
		}
	},
	/** Whether to enable verbose logging */
	verbose: false,
	/** The list of modules to bundle separately from the core application code */
	vendors: [
		'react',
		'react-dom',
		'redux',
		'react-redux',
		'redux-thunk',
		'react-router',
	],
};
